--[[
Set NPC class stereotypes chat content

This can be done by using

{"Text1","Text2","Text3",},
to set up a continuous conversation

Note that the content in [0] = {} below should not be changed.
]]--

local text = {[0] = {1,1},

---------------------- Start adding class stereotypes chat text here-------------------------

{"Why do warriors always charge into battle?", "Because thinking is for mages.", "And running away is for rogues."},
{"What’s a priest’s favorite word?", "Heal?", "Nope, it’s 'OOM.'", "Classic priest problem."},
{"Why do mages always teleport away?", "Because walking is beneath them.", "True, they’re too fancy for walking."},
{"Hunters: Great at pulling, terrible at listening.", "What’s worse than one hunter?", "Two hunters, pulling in opposite directions."},
{"Why do rogues always vanish?", "To avoid responsibility.", "And to loot the chest while you’re busy."},
{"Paladins: Saving lives one bubble at a time.", "What do you call a paladin without a shield?", "A very confused warrior."},
{"Why are druids always late?", "Because they stop to pick every flower.", "Herbs > Raids. Priorities."},
{"Warlocks: Masters of chaos and candy.", "Their summons always come with a price.", "Yeah, usually your soul."},
{"Shamans are just mages with an axe.", "And better dance moves.", "Can’t argue with that."},
{"Death knights are just edgy paladins.", "But cooler, literally.", "Frosty attitude included."},
{"Monks: Masters of kung fu and brewing.", "What’s their secret weapon?", "A well-placed keg."},
{"Why do hunters always lose their pets?", "Because they’re too busy looting.", "Hunters: Chaos in animal form."},
{"What do priests and rogues have in common?", "Nothing. One saves lives, the other ends them.", "That’s balance for you."},
{"Warriors: The masters of brute force.", "And the masters of yelling 'heal me!'"},
{"Why do mages always stand in fire?", "Because they think it’s part of their rotation.", "Fire mages: Living the theme."},
{"Rogues are just thieves with better branding.", "And a lot of stealth.", "Can’t steal what you can’t see."},
{"Why do shamans carry so many totems?", "To confuse the enemy.", "And their teammates."},
{"What’s a druid’s worst enemy?", "A tree.", "Irony at its finest."},
{"Why are monks so calm?", "Because they’re drunk half the time.", "Keg Smash solves everything."},
{"Death knights: Part warrior, part mage, all attitude.", "And they love reminding you about it."},
"Saw a warrior and a paladin arguing in the tavern. Something about who has the bigger shield.",
"Why do warriors always claim they’re tougher than paladins? At least paladins can heal their bruised egos.",
"A paladin told me their blessings are better than a warrior’s shouts. The warrior yelled louder in response.",
"I saw a warrior trying to use a shield like a paladin. They called it ‘offensive defense.’",
"Paladins say they protect the light. Warriors say they protect the loot.",
"Who wins in a duel: a warrior or a paladin? Answer: whoever runs out of stamina last.",
"Someone asked a warrior to tank like a paladin. They laughed so hard, they pulled three mobs.",
"Paladins think they’re better tanks because of their shiny armor. Warriors call it ‘walking mirrors.’",
"Warrior motto: ‘When in doubt, charge.’ Paladin motto: ‘When in doubt, bubble.’",
"I saw a warrior arguing with a paladin about DPS. They settled it by racing to the repair bill.",
"Why do mages always act so smug? Is it the fireballs or the free food?",
"I saw a mage frost nova themselves in place. They called it a ‘tactical retreat.’",
"Beware of mages offering portals. The destination might not be where you expect.",
"Someone told me a mage can make water out of thin air. Must be handy for desert treks.",
"Why do mages love polymorphing? Because nothing’s funnier than a sheep in a dungeon.",
"I heard a mage complain about their mana running out. Welcome to every other class’s reality!",
"Saw a mage solo an elite with frost spells. I guess slow and steady really does win the fight.",
"Why do mages always blink away from danger? Because it’s better than tanking with cloth armor.",
"If you see a mage summoning food, don’t ask for seconds. They’ll make you feel guilty about it.",
"Mages say they’re powerful, but even they can’t outsmart a counterspell.",
"Warrior to a paladin: ‘At least I don’t need blessings to stay alive.’ Paladin: ‘At least I have blessings.’",
"Paladins call it divine protection. Warriors call it cheating.",
"I saw a warrior trying to enchant a shield. Said they were tired of paladins getting all the sparkly stuff.",
"Why do warriors carry so many bandages? To clean up after paladins drop the ball.",
"Paladin: ‘I can heal myself.’ Warrior: ‘I can heal the enemy... with my axe.’",
"A warrior told me they don’t need shields, just bigger swords. A paladin handed them a repair bill.",
"Paladins love their auras. Warriors say their ‘aura’ is intimidation.",
"A warrior challenged a paladin to a fight. Halfway through, the paladin bubbled and sat down to eat.",
"Paladins say their light blinds enemies. Warriors say it just makes them an easier target.",
"Saw a paladin telling a warrior to hold aggro better. The warrior replied, ‘Try holding my beer.’",
"Paladins say their faith keeps them alive. Warriors say their rage does the same but louder.",
"Warrior to a paladin: ‘Your shield’s for protection, mine’s for smashing faces.’",
"Why do warriors and paladins argue so much? One fights for glory, the other for righteousness. Neither listens.",
"A paladin tried to out-tank a warrior. The warrior let them... until the healer ran out of mana.",
"Saw a warrior pick up a holy tome. Said they were gonna use it to hit harder.",
"Paladins talk about justice. Warriors talk about revenge. Both end up breaking something.",
"A paladin asked a warrior for tips on tanking. The warrior just grunted and hit the nearest mob.",
"Warriors charge into battle. Paladins walk in, glowing and sparkling. Same result, different vibe.",
"Paladin to warrior: ‘Your gear is rusty.’ Warrior: ‘Your gear is flashy.’",
"Why do warriors and paladins team up? So the paladin can bubble when the warrior messes up.",
"Some dwarf in Ironforge keeps yelling, 'You shall not pass!' Turns out, he’s guarding the keg.",
"I saw a group of adventurers throwing a ring into the lava in Blackrock Mountain. Seemed overly dramatic.",
"Someone in Goldshire is calling themselves 'Isildur’s heir.' Pretty sure they just stole a shiny necklace.",
"A gnome engineer claimed they built a mechanical Balrog. Last I saw, it was chasing them through Gnomeregan.",
"There’s a troll in the Barrens calling himself 'Gollum.' He’s obsessed with a fishing bobber.",
"I heard about an orc who tried to wield 'the Flame of Anor.' Burned his eyebrows clean off.",
"Some elf in Winterspring is looking for 'the light of Eärendil.' It’s just a really bright lantern.",
"Beware of that druid in Ashenvale. They’ve been calling themselves 'Treebeard' and growling at everyone.",
"A human warrior in Stormwind is calling their shield 'the Shard of Narsil.' It’s made of tin.",
"Rumor has it there’s a fellowship forming in Ironforge. Mostly just drunk dwarves and one very confused gnome.",
"I saw a troll shouting 'my precious!' over a green gem. Turns out it was just a shiny pebble.",
"Someone in Orgrimmar is selling lembas bread. It’s just stale biscuits wrapped in leaves.",
"Be wary of the cave in Dun Morogh. They say a balrog lives there. It’s just a very angry yeti.",
"I met a hunter calling his pet warg 'Shadowfax.' Pretty sure it’s just a wolf dyed white.",
"That elf in Darnassus keeps whispering about 'the White Council.' It’s actually just her book club.",
"There’s a hobbit-sized druid in Moonglade claiming to be a Baggins. Pretty sure he’s just a thief in disguise.",
"Someone enchanted a sword and called it Sting. Now it glows blue near kobolds. Fancy, but overkill.",
"A dwarf blacksmith in Ironforge keeps forging 'mithril mail.' It’s just shiny iron.",
"Careful in the Wetlands. There’s a swamp they’re calling 'the Dead Marshes.' It’s just really, really muddy.",
"Some mage is claiming their staff is 'Gandalf-approved.' It’s just a broomstick with a light spell.",
"I saw a mage duel a warlock. It ended with both of them out of mana, throwing rocks.",
"Why do mages always stand in the back? So they can ‘strategically observe’ while everyone else dies.",
"Ever seen a mage run out of mana mid-fight? They start throwing frostbolts like they’re snowballs.",
"Mages love to brag about their intellect. Too bad it doesn’t help them dodge fire.",
"Why do mages conjure food and water? Because cooking takes too much effort.",
"I saw a mage polymorph a boss. Turns out, sheep are really bad at holding aggro.",
"Beware of mages offering free food. It tastes like mana crystals and regret.",
"Mages think they’re clever with portals, until they send the raid group to Stonetalon by accident.",
"I heard a mage say ‘Arcane Explosion solves everything.’ I guess subtlety isn’t their strong suit.",
"Why do mages wear robes? So they can look fancy while running away.",
"Saw a mage duel a rogue. The mage blinked away, and the rogue called it a ‘coward’s sprint.’",
"Mages always talk about the power of their spells. Too bad one sneeze from a boss knocks them over.",
"I heard a mage complain about their AoE pulling too much. Congratulations, welcome to tanking!",
"Why do mages love Fireball so much? Because ‘setting things on fire’ sounds cooler than ‘doing math.’",
"If you see a mage without a wand, don’t worry. They’re probably just bad at budgeting.",
"Why do mages stack so much intellect? So they can justify all their bad decisions in dungeons.",
"Mages love to blink away from melee, but then complain when they’re alone with no mana.",
"Saw a mage sheep a mob and then forget about it. That sheep wandered off into the next zone.",
"Why do mages conjure their own food? Because spending gold on bread is apparently beneath them.",
"If you see a mage casting Mirror Image, just know they’re about to let their clones do the dying.",

---------------------- End class stereotypes chat text here-------------------------

}

return text
